import {Rokkitt } from "next/font/google";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ReduxProvider from "./GlobalRedux/reduxProvider";
import { Container } from "postcss";

const acme = Rokkitt ({ subsets: ["latin"], weight: ['400'] }); 

export const metadata = {
  title: "My website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      
      <body className={acme.className}>
        <ReduxProvider>
          <Header/>
           {children}
          <Footer/>
        </ReduxProvider>
          
      </body>
    </html>
  );
}
